---
- name: set password for user
  hosts: all
  become: yes

  tasks:
    - name: set password
      user:
        name: tushar
        update_password: always
        password: "{{ 'tushar123' | password_hash('sha512') }}"